<?php

declare(strict_types=1);

namespace App\Filament\Resources\Categories\Schemas;

use App\Filament\Forms\Components\MediaImageUpload;
use App\Filament\Forms\Components\SlugField;
use App\Models\Category;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Schema;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Validation\Rule;
use Spatie\Image\Enums\Fit;
use Spatie\Image\Image;

final class CategoryForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                MediaImageUpload::make('image')
                    ->label('Изображение')
                    ->collection('image')
                    ->required()
                    ->maxFiles(1)
                    ->processImage(static fn (Image $image): Image => $image->fit(Fit::Fill, 120, 120))
                    ->helperText('Статичное JPEG, PNG или WebP до 12 МБ. Результат: WebP 120 × 120, без обрезки и увеличения, с прозрачными полями.'),
                TextInput::make('name')
                    ->label('Название')
                    ->required()
                    ->maxLength(255),
                ...SlugField::make(autoGenerated: true),
                Select::make('parent_id')
                    ->label('Родительская категория')
                    ->placeholder('Корневая категория')
                    ->relationship('parent', 'name', modifyQueryUsing: static fn (Builder $query, ?Category $record): Builder => $query
                        ->whereNull('parent_id')
                        ->when($record, static fn (Builder $query): Builder => $query->whereKeyNot($record->getKey()))
                        ->orderBy('order'))
                    ->searchable()
                    ->preload()
                    ->disabled(static fn (?Category $record): bool => $record?->children()->exists() ?? false)
                    ->rules([Rule::exists('categories', 'id')->whereNull('parent_id')])
                    ->helperText('Доступны два уровня. Категорию с подкатегориями нельзя вложить в другую.'),
                Toggle::make('is_active')
                    ->label('Активна')
                    ->columnSpanFull(),
            ]);
    }
}
