<?php

declare(strict_types=1);

namespace App\Filament\Resources\Pages\Schemas;

use App\Filament\Forms\Components\SlugField;
use App\Support\Media\ImageMimeTypes;
use Filament\Forms\Components\RichEditor;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Components\Grid;
use Filament\Schemas\Schema;

final class PageForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Grid::make(2)
                    ->schema([
                        TextInput::make('title')
                            ->label('Заголовок')
                            ->required()
                            ->maxLength(255),
                        ...SlugField::make(autoGenerated: false),
                    ])
                    ->columnSpanFull(),
                RichEditor::make('content')
                    ->label('Содержание')
                    ->required()
                    ->fileAttachmentsAcceptedFileTypes(ImageMimeTypes::ALLOWED)
                    ->preventFileAttachmentPathTampering()
                    ->resizableImages()
                    ->columnSpanFull(),
                Toggle::make('is_active')
                    ->label('Активна')
                    ->columnSpanFull(),
            ]);
    }
}
