<?php

declare(strict_types=1);

namespace App\Filament\Resources\Pages\Schemas;

use App\Filament\Forms\Components\SlugField;
use Filament\Forms\Components\RichEditor;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Schema;

final class PageForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('key')
                    ->label('Системный ключ')
                    ->required()
                    ->alphaDash()
                    ->maxLength(100)
                    ->unique(ignoreRecord: true),
                TextInput::make('title')
                    ->label('Заголовок')
                    ->required()
                    ->maxLength(255),
                ...SlugField::make(autoGenerated: false),
                RichEditor::make('content')
                    ->label('Содержание')
                    ->required()
                    ->fileAttachmentsAcceptedFileTypes(['image/jpeg', 'image/png', 'image/webp'])
                    ->preventFileAttachmentPathTampering()
                    ->resizableImages()
                    ->columnSpanFull(),
                Toggle::make('is_active')
                    ->label('Активна')
                    ->columnSpanFull(),
            ]);
    }
}
