<?php

declare(strict_types=1);

namespace App\Filament\Forms\Components;

use Filament\Actions\Action;
use Filament\Forms\Components\Hidden;
use Filament\Forms\Components\TextInput;
use Filament\Schemas\Components\Utilities\Get;
use Filament\Schemas\Components\Utilities\Set;
use Filament\Support\Icons\Heroicon;

final class SlugField
{
    /**
     * @return array{Hidden, TextInput}
     */
    public static function make(bool $autoGenerated): array
    {
        $editableState = 'slug_is_editable';

        $input = TextInput::make('slug')
            ->label('ЧПУ')
            ->helperText($autoGenerated
                ? 'Оставьте пустым, чтобы сформировать автоматически из заголовка.'
                : 'Чтобы изменить ЧПУ, сначала разблокируйте поле.')
            ->readOnly(fn (Get $get): bool => ! (bool) $get($editableState))
            ->suffixAction(
                Action::make('toggleSlugEditing')
                    ->label(fn (Get $get): string => $get($editableState) ? 'Заблокировать ЧПУ' : 'Разблокировать ЧПУ')
                    ->icon(fn (Get $get): Heroicon => $get($editableState) ? Heroicon::OutlinedLockOpen : Heroicon::OutlinedLockClosed)
                    ->color('gray')
                    ->action(function (Get $get, Set $set) use ($editableState): void {
                        $set($editableState, ! (bool) $get($editableState));
                    }),
            )
            ->alphaDash()
            ->maxLength(255)
            ->unique(ignoreRecord: true);

        if ($autoGenerated) {
            $input->nullable();
        } else {
            $input->required();
        }

        return [
            Hidden::make($editableState)
                ->default(false)
                ->dehydrated(false),
            $input,
        ];
    }
}
