<?php

declare(strict_types=1);

namespace App\Filament\Resources\Articles\Schemas;

use App\Filament\Forms\Components\MediaImageUpload;
use App\Filament\Forms\Components\SlugField;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\RichEditor;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Schema;

final class ArticleForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                MediaImageUpload::make('image')
                    ->label('Изображение')
                    ->collection('image')
                    ->required()
                    ->maxFiles(1)
                    ->helperText('Статичное JPEG, PNG или WebP до 12 МБ. Для карточки автоматически создаётся миниатюра 410 × 273.'),
                TextInput::make('title')
                    ->label('Заголовок')
                    ->required()
                    ->maxLength(255),
                ...SlugField::make(autoGenerated: true),
                DatePicker::make('published_at')
                    ->label('Дата публикации')
                    ->required(),
                Textarea::make('excerpt')
                    ->label('Краткое описание')
                    ->rows(4)
                    ->columnSpanFull(),
                RichEditor::make('content')
                    ->label('Содержание')
                    ->required()
                    ->fileAttachmentsAcceptedFileTypes(['image/jpeg', 'image/png', 'image/webp'])
                    ->preventFileAttachmentPathTampering()
                    ->resizableImages()
                    ->columnSpanFull(),
                Toggle::make('is_active')
                    ->label('Активна')
                    ->columnSpanFull(),
            ]);
    }
}
