@extends('layouts.base')

@section('content')
    @include('home.partials.hero-slider')
    @include('home.partials.benefits')
    @include('home.partials.featured-categories')
    @include('home.partials.banner-wide')
    @include('home.partials.special-offers', ['title' => 'Хиты продаж', 'productOrder' => [0, 2, 1, 4, 3, 5]])
    @include('home.partials.banner-double')
    @include('home.partials.special-offers', ['title' => 'Новинки', 'productOrder' => [3, 1, 4, 0, 5, 2]])
    @include('home.partials.banner-triple')
    @include('home.partials.special-offers', ['title' => 'Товары со скидкой', 'productOrder' => [2, 5, 4, 0, 3, 1]])
    @include('home.partials.latest-blog')
    @include('home.partials.company-story')
@endsection
