@extends('layouts.base')

@section('content')
    @include('home.partials.hero-slider')
    @include('home.partials.benefits')
    @include('home.partials.featured-categories')
    @include('home.partials.banner-wide')
    @include('home.partials.special-offers')
    @include('home.partials.banner-double')
    @include('home.partials.special-offers')
    @include('home.partials.banner-triple')
    @include('home.partials.special-offers')
    @include('home.partials.latest-blog')
    @include('home.partials.company-story')
@endsection
