<?php

declare(strict_types=1);

namespace App\Filament\Resources\News\Schemas;

use App\Filament\Forms\Components\MediaImageUpload;
use App\Filament\Forms\Components\SlugField;
use App\Support\Media\ImageMimeTypes;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\RichEditor;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Components\Grid;
use Filament\Schemas\Schema;
use Spatie\Image\Image;

final class NewsForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                MediaImageUpload::make('image')
                    ->label('Изображение')
                    ->collection('image')
                    ->required()
                    ->maxFiles(1)
                    ->processImage(static fn (Image $image): Image => $image)
                    ->helperText('Статичное JPEG, PNG или WebP до 12 МБ. Для карточки автоматически создаётся миниатюра 410 × 273.')
                    ->columnSpanFull(),
                Grid::make(2)
                    ->schema([
                        TextInput::make('title')
                            ->label('Заголовок')
                            ->required()
                            ->maxLength(255),
                        ...SlugField::make(autoGenerated: true),
                    ])
                    ->columnSpanFull(),
                DatePicker::make('published_at')
                    ->label('Дата публикации')
                    ->required(),
                Textarea::make('excerpt')
                    ->label('Краткое описание')
                    ->rows(4)
                    ->columnSpanFull(),
                RichEditor::make('content')
                    ->label('Содержание')
                    ->required()
                    ->fileAttachmentsAcceptedFileTypes(ImageMimeTypes::ALLOWED)
                    ->preventFileAttachmentPathTampering()
                    ->resizableImages()
                    ->columnSpanFull(),
                Toggle::make('is_active')
                    ->label('Активна')
                    ->columnSpanFull(),
            ]);
    }
}
